Milestone 5
wintan1418/calculator-react pull request #4
Opened 2021-08-02 11:22 UTC by wintan1418

The App component is a  stateful parent component.
 I have made a class component. Initialized its state in the constructor with three properties: total, next and operation.
just like in the calculate.js module. By default, they should all be set to null.
Implemented a render function that should display Display and ButtonPanel.
Implemented the handleClick function which takes the button name as an argument and changes the state based on the result of the calculate function.
Passed the total or next value to Display the current result.
Passed handleClick as a click handler property to ButtonPanel.

Implemented the handleClick function which takes button name as an argument and returns clickHandler from props.
Passed the clickHandler property to each button in the panel.

Implemented the handleClick function which takes button name as an argument and returns clickHandler from props.
Used the onClick event to attach the handleClick event to the button.

2021-08-02 12:43 UTC, george-shammar requested changes
Hi @wintan1418 , 

Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there! :+1: 


Your calculator is not working as it should. This is the last milestone but unfortunately, most of the required changes are carry overs from the previous milestones. Perhaps you broke your code and created new bugs in the process of implementing this milestone. Please see below:


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-02 12:43 UTC, george-shammar commented on src/logic/operate.js
> +      throw new Error(`Wrong operator ${op}`);
Nice effort so far. :+1: You've put in a lot work into this.

- [ ] The `division`, `%` operators generate the error below. 
![error](https://user-images.githubusercontent.com/70150423/127862384-152672aa-2355-41dc-a107-9914db11357c.png)

- [ ]  The `X` operator does not function at all.

2021-08-02 12:43 UTC, george-shammar commented on src/component/App.js
> +
- [ ] The way this prop is coded and passed to the Display component is producing an awkward output. Please see below. What I tried to do was add two numbers together.
![Screenshot 2021-08-02 at 12-37-05 React App](https://user-images.githubusercontent.com/70150423/127863024-217f5faa-bad0-47f5-a531-5504fea032a0.png)
You have something like the image above for all your calculator operations. Buttons are concatenated with the operations.

2021-08-03 14:28 UTC, mahmoud717 approved these changes
### STATUS: APPROVED ✔️ ✔️ 

**hi @wintan1418**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

2021-08-03 14:29 UTC, merged